### ISSUE TITLE
Consider adopting conventional commit messages

### ISSUE THREAD

**Issue by mih** [datalad/datasalad#10]
https://www.conventionalcommits.org/en/v1.0.0/

This would make #8 unnecessary, still achieve a good changelog, and enable automated releases (e.g., via release-please).

https://pypi.org/project/commitizen/ seems to be a helper candidate. Demo: https://commitizen-tools.github.io/commitizen/

**Comment by mih** [comment]
https://github.com/datalad/datalad-next/pull/700 is an example PR with a commit message validation (which also happens to add the CI workflow for that check).

Notice how the commit listing at https://github.com/datalad/datalad-next/pull/700/commits already has some potential to be a good PR description. The actual PR description is purposefully left empty.

**Comment by mih** [comment]
I ran through a full release cycle with datalad-next 1.4.1 to see the tooling in action. Here is how I feel:

### The bad stuff

- The resulting changelog looks auto-generated. Not far from the feel of the one in DataLad core. See https://github.com/datalad/datalad-next/blob/main/CHANGELOG.md#141-2024-05-22
- I could not tune the built-in conventional commit "commitizen", but had to go fully custom to make small tweaks.
- Most structured information from the commit message is ignored. It feels like it could be made accessible for the changelog template, but it seems to be stretching the design of commitizen a bit (much). This means that a changelog item is largely the subject line (reformatted)

### The good stuff

- There is ZERO relevant information in the PR outside of commits. This is perfect.
- The change-type, scope, description onliner conveys a lot of information in very few chars
- Linking the associated commit (rather than a PR, issues, github account name) is a meaningful level of indirection. The commit can/does have all this information, and this information will be everywhere that commit it.
- Putting the commit (message) front and center has benefits beyond changelog generation. It is a useful, implicit constraint on what should be a (single) commit.
- There is no separate "I only still need to write the changelog" step. Instead the focus is on (iteratively) composing meaningfully structured, well-described changesets.

@mih's conclusion: the good outweighs the bad.

**Comment by jsheunis** [comment]
I agree. I particularly like the focus on thorough and self-contained commit messages rather than injecting transient information into a PR description.

**Comment by mih** [comment]
`datalad-next` has switched from `scriv` to `commitizen`.

**Comment by mslw** [comment]
I am of two minds about this.
- I guess we can only find out how good it is in practice -- through practice, so I'm happy to see it being tried
- I agree with your evaluation, both good stuff and bad stuff
- I am all for editing rebase sequences, but I am not fully convinced that one feat or fix can always be squashed into one commit
- Implementing the convention may shift focus to describing changesets in commits, but I do not think it automatically translates to having useful commit messages; related: https://hachyderm.io/@sanityinc/112326951936274631

**Comment by mih** [comment]
Thanks for the feedback. I agree that salvation will not come from just formatting commit messages in a particular fashion.

I have no tried this approach in datalad-next for three weeks, and I find it to be fairly unintrusive. I overall like being nudged to think about the framing of individual commits. I find the resulting patch series to be universally clearer.

The most perceivable practical "downside" is that it become much harder to justify that "one last commit that fixes it just enough to pass that one last tests". I think this is painful, but ultimately a benefit.

I think we should adopt this and collect evidence for switching to another system, if needed.
